name: CI

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

env:
  HOST: 106.12.87.55
  USERNAME: root
  PORT: 22
  SSH_KEY:  ${{secrets.BD_SSH_KEY}}
  BACKEND_SRC: "**"
  BACKEND_TARGET: nideshop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install yarn dependencies
        run: |
          echo Node.js runtime version: $(node -v)
          yarn
      - name: Run unit test
        run: yarn test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release branch code
      - uses: actions/checkout@v2
      - name: SCP Command to Transfer Files
          uses: appleboy/scp-action@master
          with:
            host: ${{ env.HOST }}
            username: ${{ env.USERNAME }}
            key: ${{ env.SSH_KEY }}
            source: ${{ env.BACKEND_SRC }}
            target: ${{ env.BACKEND_TARGET }}
            strip_components: 1
            rm: true
      - name: SSH Remote Commands
          uses: appleboy/ssh-action@master
          with:
            host: ${{ env.HOST }}
            username: ${{ env.USERNAME }}
            key: ${{ env.SSH_KEY }}
            script: |
              cd ${{ env.BACKEND_TARGET }}
              ls -alhS
              yarn && yarn build
